=== caste-matteo/EasyFood/Cuciniamo/src/cuciniamo.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT Ricetta (Opzioni, (Ricetta|Apri)*, ListaIngredienti, Procedimento) >
<!ATTLIST Ricetta nome CDATA #REQUIRED >

<!ELEMENT Opzioni (Salva|Autore|Categoria|Difficolta|Tempo|Privata|Strumenti|Festivita|Promemoria)* >

<!ELEMENT Salva (#PCDATA)>
<!ELEMENT Autore (#PCDATA)>
<!ELEMENT Categoria (Superiore?, Inferiore?)>
<!ELEMENT Superiore (#PCDATA)>
<!ELEMENT Inferiore (#PCDATA)>
<!ELEMENT Difficolta (#PCDATA)>
<!ELEMENT Tempo (#PCDATA)>
<!ELEMENT Privata (#PCDATA)>
<!ELEMENT Strumenti (Strumento)*>
<!ELEMENT Strumento (#PCDATA)>
<!ELEMENT Festivita (#PCDATA)>
<!ELEMENT Promemoria (#PCDATA)>

<!ELEMENT Apri (File | Database) >
<!ELEMENT File (#PCDATA)>
<!ELEMENT Database (#PCDATA)>
<!ATTLIST Database utente CDATA #IMPLIED >

<!ELEMENT ListaIngredienti (Ingrediente)+ >
<!ELEMENT Ingrediente EMPTY >
<!ATTLIST Ingrediente 
	tipo CDATA #REQUIRED
	quantita CDATA #IMPLIED 
	misura CDATA #IMPLIED >

<!ELEMENT Procedimento (#PCDATA) >

=== caste-matteo/EasyFood/Cuciniamo/test/ricettainxml.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Ricetta SYSTEM "../src/cuciniamo.dtd">
<!--Ricetta nome="Torta alla panna" xmlns:xs="oud.xsd" xs:noNameSpaceSchemaLocation="out.xsd"-->
<Ricetta nome="Torta alla panna" >
	
	<Opzioni>
		<Salva>tortallapanna.txt</Salva>
		<Categoria>
			<Superiore>Dolci</Superiore>
			<Inferiore>Torte</Inferiore>
		</Categoria>
		<Difficolta>7</Difficolta>
		<Autore>ptommasi</Autore>
		<Tempo>110</Tempo>
		<Privata>true</Privata>
		<Strumenti>
			<Strumento>marisa</Strumento>
			<Strumento>fruste elettriche</Strumento>
		</Strumenti>
		<Festivita>San Valentino</Festivita>
		<Promemoria>Forno a 180Â°</Promemoria>
	</Opzioni>
	
	<Apri>
		<NomeRicetta>Pandispagna</NomeRicetta>
	</Apri>
	
	<ListaIngredienti>
		<Ingrediente tipo="zucchero" quantita="110" misura="grammi" />
	</ListaIngredienti>

	<Procedimento>Fai la torta</Procedimento>
	
</Ricetta>
